config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :api do
    resources :conferences, :defaults => { :format => 'json' }
    resources :events, :defaults => { :format => 'json' } do
      collection do
        post 'update_promoted'
        post 'update_view_counts'
        post 'update_feeds'
      end
    end
    resources :recordings, :defaults => { :format => 'json' }
    resources :news, :defaults => { :format => 'json' }
  end

  namespace :public do
    get :index, path: '/', defaults: { format: 'json' }
    get :oembed
    resources :conferences, only: [:index, :show], defaults: { format: 'json' }
    constraints(id: %r'[^/]+') do
      resources :events, only: %i(index show), defaults: { format: 'json' } do
        get :recent, defaults: { format: 'json' }, on: :collection
        get :search, defaults: { format: 'json' }, on: :collection
        get :popular, defaults: { format: 'json' }, on: :collection
        get :unpopular, defaults: { format: 'json' }, on: :collection
      end
    end
    resources :recordings, only: %i(index show), defaults: { format: 'json' } do
      collection do
        post 'count'
      end
    end
  end

  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  post "/graphql", to: "graphql#execute"
  get "/graphql", to: "graphql#execute"

  scope module: 'frontend' do
    root to: 'home#index'
    if Rails.env.production?
      get '404', to: 'home#page_not_found'
    end
    get '/about', to: 'home#about'
    get '/search', to: 'search#index'
    get '/sitemap.xml', to: 'sitemap#index', defaults: { format: 'xml' }

    get '/v/:slug', to: 'events#show', as: :event, :constraints => { slug: %r'[^/]+' }
    get '/postroll/:slug', to: 'events#postroll', as: :postroll, :constraints => { slug: %r'[^/]+' }
    get '/v/:slug/oembed', to: 'events#oembed', as: :oembed_event, :constraints => { slug: %r'[^/]+' }
    get '/v/:slug/playlist', to: 'events#playlist_conference', as: :playlist_conference, :constraints => { slug: %r'[^/]+' }
    get '/v/:slug/audio', to: 'events#audio_playlist_conference', as: :audio_playlist_conference, :constraints => { slug: %r'[^/]+' }
    get '/v/:slug/related', to: 'events#playlist_related', as: :playlist_related, :constraints => { slug: %r'[^/]+' }

    get '/c/:acronym', to: 'conferences#show', as: :conference
    get '/c/:acronym/:tag', to: 'conferences#show', as: :conference_tag, :constraints => { tag: %r'[^/]+' }

    get '/a', to: 'conferences#all', as: :all_conferences
    get '/b', to: 'conferences#browse', as: :browse_start
    get '/b/*slug', to: 'conferences#browse', as: :browse

    get '/recent', to: 'recent#index'
    get '/popular', to: 'popular#index'
    get '/popular/:year', to: 'popular#index'
    get '/unpopular', to: 'unpopular#index'
    get '/unpopular/:year', to: 'unpopular#index'

    get '/tags/:tag', to: 'tags#show', as: :tag

    get '/news.atom', to: 'news#index', defaults: { format: 'xml' }, as: :news
    get '/updates.rdf', to: 'feeds#updates', defaults: { format: 'xml' }
    get '/podcast-audio-only.xml', to: 'feeds#podcast_audio', defaults: { format: 'xml' }

    get '/podcast-(:quality).xml', to: 'feeds#podcast',
        defaults: { format: 'xml' }, :constraints => { quality: %r'\w\w' }
    get '/podcast-archive-(:quality).xml', to: 'feeds#podcast_archive',
        defaults: { format: 'xml' }, :constraints => { quality: %r'\w\w' }

    get '/c/:acronym/podcast/:mime_type-(:quality).xml', to: 'feeds#podcast_folder',
        defaults: { format: 'xml' }, :constraints => { quality: %r'\w\w' }, as: :podcast_folder_video_feed
    get '/c/:acronym/podcast/:mime_type-master.xml', to: 'feeds#podcast_folder',
        defaults: { format: 'xml', quality: 'master' }, as: :podcast_folder_video_master_feed
    get '/c/:acronym/podcast/:mime_type.xml', to: 'feeds#podcast_folder',
        defaults: { format: 'xml' }, :constraints => { quality: %r'\w\w' }, as: :podcast_folder_feed

    get '/podcast/:slug/:mime_type', to: 'feeds#podcast_folder', defaults: { format: 'xml' }, as: :old_podcast_folder_feed
    get '/podcast.xml', to: 'feeds#podcast_legacy', defaults: { format: 'xml' }
    get '/podcast-archive.xml', to: 'feeds#podcast_archive_legacy', defaults: { format: 'xml' }
  end

end

app/models/frontend.rb
module Frontend
end

app/controllers/api/events_controller.rb
class Api::EventsController < ApiController
  protect_from_forgery except: %i(create update_promoted)
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # POST /api/events.json
  def index
    @events = Event.all
  end

  # GET /api/events/1.json
  # GET /api/events/654331ae-1710-42e5-bdf4-65a03a80c614.json
  def show
  end

  # GET /api/events/new
  def new
    @event = Event.new
  end

  # GET /api/events/1/edit
  # GET /api/events/654331ae-1710-42e5-bdf4-65a03a80c614/edit
  def edit
  end

  # POST /api/events.json
  def create
    acronym = params['acronym']
    conference = Conference.find_by! acronym: acronym
    @event = conference.events.build event_params

    respond_to do |format|
      if create_event(params)
        format.json { render json: @event, status: :created }
      else
        Rails.logger.info("JSON: failed to create event: #{@event.errors.inspect}")
        format.json { render json: @event.errors.messages, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /api/events/1.json
  # PATCH/PUT /api/events/654331ae-1710-42e5-bdf4-65a03a80c614.json
  def update
    fail ActiveRecord::RecordNotFound unless @event

    respond_to do |format|
      if @event.update(event_params)
        format.json { render :show, status: :ok }
      else
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api/events/1.json
  # DELETE /api/events/654331ae-1710-42e5-bdf4-65a03a80c614.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  def update_feeds
    Feed::PodcastWorker.perform_async
    Feed::LegacyWorker.perform_async
    Feed::AudioWorker.perform_async
    Feed::ArchiveWorker.perform_async
    Feed::ArchiveLegacyWorker.perform_async
    render json: { status: 'ok' }
  end

  def update_promoted
    Event.update_promoted_from_view_count
    render json: { status: 'ok' }
  end

  def update_view_counts
    Event.update_view_counts
    render json: { status: 'ok' }
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    if params[:id] =~ /\A[0-9]+\z/
      @event = Event.find(params[:id])
    else
      @event = Event.find_by(guid: params[:id])
    end
  end

  def create_event(params)
    @event.set_image_filenames(params[:thumb_url], params[:poster_url], params[:timeline_url], params[:thumbnails_url])
    @event.save!
  rescue ActiveRecord::RecordInvalid
    false
  end

  def event_params
    params.require(:event).permit(:guid, :slug,
      :title, :subtitle, :link,
      :original_language,
      :thumb_filename, :poster_filename, :timeline_filename, :thumbnails_filename,
      :conference_id,
      :metadata,
      :description, :date,
      :doi,
      { persons: [] }, { tags: [] },
      :promoted, :release_date)
  end
end

app/controllers/frontend/conferences_controller.rb
module Frontend
  class ConferencesController < FrontendController
    SORT_PARAM = {
      'name' => 'title',
      'duration' => 'duration',
      'date' => 'date desc, release_date desc',
      'view_count' => 'view_count desc'
    }.freeze

    before_action :check_sort_param, only: %w(show)

    def all
      @conferences = conferences_with_events.order('event_last_released_at DESC')
      respond_to do |format|
        format.html { render :list }
      end
    end

    def browse
      return show if slug_matches_conference

      @folders = conferences_folder_tree_at(params[:slug] || '')
      return redirect_to root_url if @folders.blank?
      respond_to do |format|
        format.html { render :browse }
      end
    end

    def show
      @conference = Frontend::Conference.find_by!(acronym: params[:acronym]) unless @conference
      if params[:tag]
        @tag = params[:tag]
        @events = @conference.events.includes(:conference).reorder(sort_param).select { |event| event.tags.include? @tag }
      else
        @events = @conference.events.includes(:conference).reorder(sort_param)
      end

      respond_to do |format|
        format.html { render :show }
      end
    end

    private

    def slug_matches_conference
      @conference = Frontend::Conference.find_by(slug: params[:slug])
    end

    def conferences_folder_tree_at(path)
      tree = FolderTree.new
      tree.build(conferences_with_events.pluck(:id, :slug))
      folders = tree.folders_at(path)
      fail ActiveRecord::RecordNotFound unless folders
      tree.sort_folders(folders)
    end

    def conferences_with_events
      Conference.where('downloaded_events_count > 0')
    end

    def sort_param
      return SORT_PARAM[@sorting] if @sorting
      'view_count desc'
    end

    def check_sort_param
      return unless params[:sort]
      return unless SORT_PARAM.keys.include?(params[:sort])
      @sorting = params[:sort]
    end
  end
end

app/controllers/frontend/events_controller.rb
module Frontend
  class EventsController < FrontendController
    before_action :load_event

    def show
      respond_to { |format| format.html }
    end

    def playlist_related
      @playlist = Playlist.related(@event)
      respond_to { |format| format.html { render :playlist } }
    end

    def playlist_conference
      @playlist = Playlist.for_conference(@conference, lead_event: @event)
      respond_to { |format| format.html { render :playlist } }
    end

    def audio_playlist_conference
      @playlist = Playlist.for_conference(@conference, lead_event: @event, audio: true)
      respond_to { |format| format.html { render :playlist } }
    end

    def postroll
      @events = related_events(3)
      render layout: false
    end

    # videoplayer suitable for embedding in an iframe
    def oembed
      @width = params[:width] || view_context.aspect_ratio_width
      @height = params[:height] || view_context.aspect_ratio_height
      response.headers.delete 'X-Frame-Options'
      render layout: 'frontend/oembed'
    end

    private

    def related_events(n)
      return Event.find(@event.related_event_ids(n)) if @event.metadata['related'].present?
      @event.next_from_conference(n)
    end

    def load_event
      @event = Frontend::Event.find_by!(
        "slug = ? OR guid = ? OR slug ILIKE ?", 
        params[:slug], params[:slug], params[:slug] + '%'
      )

      if params[:slug] != @event.slug
        redirect_to event_url(slug: @event.slug)
      end

      @conference = @event.conference
      @player = ''
      if params[:player] && /\A[a-z]+\Z/.match(params[:player])
        @player = '_' + params[:player]
      end
    end
  end
end

app/controllers/frontend/feeds_controller.rb
module Frontend
  class FeedsController < FrontendController
    before_action :set_conference, only: %i(podcast_folder)
    before_action :set_quality, only: %i(podcast podcast_archive podcast_folder)

    def podcast
      xml = WebFeed.find_by!(key: :podcast, kind: @quality).content

      respond_to do |format|
        format.xml { render xml: xml }
      end
    end

    def podcast_legacy
      xml = WebFeed.find_by!(key: :podcast_legacy).content

      respond_to do |format|
        format.xml { render xml: xml }
      end
    end

    def podcast_archive
      xml = WebFeed.find_by!(key: :podcast_archive, kind: @quality).content

      respond_to do |format|
        format.xml { render xml: xml }
      end
    end

    def podcast_archive_legacy
      xml = WebFeed.find_by!(key: :podcast_archive_legacy).content

      respond_to do |format|
        format.xml { render xml: xml }
      end
    end

    def podcast_folder
      kind = WebFeed.folder_key(@conference, @quality, @mime_type)
      xml = WebFeed.find_by!(key: :podcast_folder, kind: kind).content

      respond_to do |format|
        format.xml { render xml: xml }
      end
    end

    def podcast_audio
      xml = WebFeed.find_by!(key: :podcast_audio).content

      respond_to do |format|
        format.xml { render xml: xml }
      end
    end

    # rss 1.0 last 100 feed
    def updates
      xml = WebFeed.find_by!(key: :rdftop100).content

      respond_to do |format|
        format.xml { render xml: xml }
      end
    end

    private

    def set_conference
      @conference = if params[:acronym]
                      Frontend::Conference.find_by!(acronym: params[:acronym])
                    elsif params[:slug]
                      Frontend::Conference.find_by!(slug: params[:slug])
                    end
      fail ActiveRecord::RecordNotFound unless @conference

      _, @mime_type = @conference.mime_type_names.find { |_,n| n == params[:mime_type] }
      fail ActiveRecord::RecordNotFound unless @mime_type
    end

    def set_quality
      @quality = params[:quality] || ''
    end
  end
end

app/controllers/frontend/home_controller.rb
module Frontend
  class HomeController < FrontendController
    helper_method :recent_events_for_conference
    CONFERENCE_LIMIT = 9
    EVENT_LIMIT = 3

    def index
      @news = Frontend::News.recent(1).first
      @hours_count = Frontend::Event.sum(:duration)/(60*60)
      @recordings_count = Frontend::Recording.count
      @events_count = Frontend::Event.count
      @conferences_count = Frontend::Conference.count

      @recent_conferences = Frontend::Conference.with_recent_events(CONFERENCE_LIMIT)

      @currently_streaming = Frontend::Conference.currently_streaming

      respond_to { |format| format.html }
    end

    def page_not_found
      respond_to do |format|
        format.json { head :no_content }
        format.xml { render xml: { status: :error } }
        format.all { render :page_not_found, status: 404, slug: params[:slug] }
      end
    end

    private

    def recent_events_for_conference(conference)
      conference.events.released.includes(:conference).limit(EVENT_LIMIT)
    end
  end
end

app/helpers/frontend/application_helper.rb
module Frontend
  module ApplicationHelper
    require 'uri'

    def oembed_api_event_url(event)
      (public_oembed_url(url: event_url(slug: event.slug))).freeze
    end

    def twitter_url(title, url)
      'https://twitter.com/home?status='.freeze + URI.encode_www_form_component(title + ': ' + url)
    end

    def facebook_url(title, url)
      'https://www.facebook.com/sharer/sharer.php?t='.freeze + URI.encode_www_form_component(title) + '&u=' + URI.encode_www_form_component(url)
    end

    def diaspora_url(title, url)
      'https://share.diasporafoundation.org/?title='.freeze + URI.encode_www_form_component(title).gsub(/\+/, '%20') + '&url=' + URI.encode_www_form_component(url)
    end

    def mail_url(title, url)
      content = ERB::Util.url_encode(title + ': ' + url)
      subject = ERB::Util.url_encode(title)
      URI::MailTo.build(['', [['subject', subject], ['body', content]]]).to_s.freeze
    end

    def breadcrumbs_trail
      path = if @conference
               @conference.slug
             elsif @folders
               @folders.last.parent_path
             else
               ''.freeze
             end
      parts = path.split('/')
      return if parts.blank?
      if @playlist
        parts += ['playlist']
      elsif @event
        parts += ['event']
      elsif @tag
        parts += [@tag]
      end
      current = parts.pop
      yield parts.map!(&:freeze), current.freeze
    end

    # TODO which video to prefer?
    def opengraph_video(recordings)
      recordings.first.try(:url)
    end

    def keywords
      if @event&.tags
        [@event.tags, I18n.t('custom.header.keywords')].join(', ')
      else
        I18n.t('custom.header.keywords')
      end
    end

    def duration_in_minutes(duration)
      "#{duration / 60} min" if duration.positive?
    end

    def video_for_flash(recordings)
      url = recordings.find { |recording| recording.mime_type == 'video/mp4' }.try(:url)
      if url.present?
        h(url)
      elsif recordings.present?
        h(recordings.first.url)
      else
        # :(
        ''
      end
    end

    def aspect_ratio_width(high = true)
      case @conference.aspect_ratio
      when /16:9/
        high ? '640' : '188'
      when /4:3/
        high ? '400' : '120'
      end
    end

    def aspect_ratio_height(high = true)
      case @conference.aspect_ratio
      when /16:9/
        high ? '360' : '144'
      when /4:3/
        high ? '300' : '90'
      end
    end

    def aspect_ratio_height_vw
      case @conference.aspect_ratio
      when /16:9/
        '56.25vw'
      when /4:3/
        '75vw'
      end
    end

    def persons_icon(persons)
      if persons.length <= 1
        'icon-user-light'.freeze
      else
        'icon-users-light'.freeze
      end
    end

    def display_release_date_title(event)
      return 'event and release date' if event.released_on_event_day?
      return 'event date' if event.date

      'video release date'
    end

    def relive_data(event, width, height)
      data = { width: width, height: height, m3u8: event.relive['playlist'] }
      return data unless event.relive['sprites']

      data.merge!(
        sprites: event.relive['sprites']['url'],
        'sprites-n': event.relive['sprites']['n'],
        'sprites-cols': event.relive['sprites']['cols'],
        'sprites-interval': event.relive['sprites']['interval']
      )
    end

    def video_player_ivars(args = {})
      {
        height: '100%',
        width: '100%',
        event: @event
      }.merge(args)
    end

    def stretching
      'responsive'
    end
  end
end

app/views/frontend/events/_event.html.haml
- cache([event.conference, event]) do
  .event-preview
    = render partial: 'frontend/shared/event_thumb', locals: { event: event }
    = render partial: 'frontend/shared/event_metadata', locals: { event: event }

app/views/frontend/events/playlist.html.haml
- content_for :title do
  Playlist for
  = %("#{@playlist.title}")

- content_for :body_class do
  page-show page-show-playlist

- content_for :head do
  - if @playlist.conference
    = render partial: 'frontend/shared/folder_feeds', locals: { conference: @playlist.conference }

- cache([@playlist.playlist]) do
  .container-fluid
    .player-header
      - if @conference&.logo_url
        %a.thumbnail.conference{href: conference_path(acronym: @conference.acronym)}
          %img{src: @conference.logo_url, alt: 'conference logo'}
          - if @conference.logo_does_not_contain_title
            .caption
              = @conference.title
      - else 
        =@conference.title

      %h1
        Playlist
        = %("#{@playlist.title}")

    - if @playlist.audio?
      .player.audio
        = render partial: 'frontend/shared/player_playlist_audio', locals: { playlist: @playlist }

    - else
      .player.video
        .kiosk
        = render partial: 'frontend/shared/player_playlist_video', locals: video_player_ivars(playlist: @playlist)

    %h2.event_title
      = @playlist.lead_event.title
  
    %p.persons
      = render partial: 'frontend/shared/event_persons', locals: { persons: @playlist.lead_event.persons }
      
    %p
      = simple_format(@playlist.lead_event.description, class: :description)

app/views/frontend/events/postroll.html.haml
.postroll
  %h4 continue…
  .container-fluid
    .row
      .col-xs-12
        %b
          Related to
          - if @event.link
            = link_to @event.title, @event.link
          - else
            = @event.title

    .row
      - @events.each do |event|
        .col-xs-4.event
          = render partial: 'frontend/shared/event_title', locals: { event: event }
          = render partial: 'frontend/shared/event_thumb', locals: { event: event }

app/views/frontend/events/show.html.haml
- content_for :title do
  = @event.title

- content_for :body_class do
  page-show

- content_for :head do
  %meta{property: 'og:title', content: @event.title}
  %meta{property: 'og:type', content: 'video.other'}
  %meta{property: 'og:url', content: event_path(slug: @event.slug)}
  %meta{property: 'og:image', content: @event.poster_url}
  %meta{property: 'og:video', content: opengraph_video(@event.videos_sorted_by_language)}
  %meta{property: 'og:video:release_date', content: @event.release_date}
  %meta{property: 'og:description', content: @event.short_description}
  - @event.persons.each do |speaker|
    %meta{property: 'author', content: speaker}
  %link{rel: 'canonical', href: event_path(slug: @event.slug)}
  - if @event.preferred_recording
    %script{type: 'application/ld+json'}
      :plain
        {
          "@context": "https://schema.org",
          "@type": "VideoObject",
          "name": "#{@event.title}",
          "description": "#{@event.short_description}",
          "thumbnailUrl": "#{@event.poster_url}",
          "uploadDate": "#{@event.release_date}",
          "duration": "PT#{@event.duration}S",
          "publisher": {
            "@type": "Organization",
            "name": "media.ccc.de",
              "logo": {
              "@type": "ImageObject",
              "url": "/apple-touch-icon.png",
              "width": 180,
              "height": 180
            }
          },
          "contentUrl": "#{@event.preferred_recording.filename}",
          "embedUrl": "#{oembed_api_event_url(@event)}"
        }
  = render partial: 'frontend/shared/folder_feeds', locals: { conference: @conference }
  != "<link href='#{oembed_api_event_url(@event)}' rel='alternate' title='media.ccc.de oembed profile' type='application/json+oembed'>"

- if current_admin_user
  - content_for :navbar do
    .nav.navbar-form.navbar-right.button-wrapper
      %a.form-control.btn.btn-default{href: edit_admin_event_path(@event), data: { turbolinks: "false" }}
        %span.icon.icon-edit

- content_for :description do
  %meta{name: 'description', content: @event.short_description}

- cache([@event.conference, @event, @player, current_admin_user]) do
  .container-fluid
    .player-header
      .conference
        - if @conference&.logo_url
          %a.thumbnail.conference{href: conference_path(acronym: @conference.acronym)}
            %img{src: @conference.logo_url, alt: 'conference logo'}
            - if @conference.logo_does_not_contain_title
              .caption
                = @conference.title
        - else
          =@conference.title
      %h1
        = @event.title
      - unless @event.subtitle.blank?
        %h2
          = @event.subtitle

    %p.persons
      = render partial: 'frontend/shared/event_persons', locals: { persons: @event.persons }

    - if @event.recordings.video.present?
      .player.video{'data-aspect-ratio' => @conference.aspect_ratio}
        .kiosk
        = render partial: 'frontend/shared/player_video' + @player, locals: video_player_ivars

      - if !@event.tags.nil? && @event.tags.length > 3 
        - @event.tags[3,2].reverse.each do |tag|
          != link_for(@conference, tag)

      Playlists:
      = link_to "'#{@conference.acronym}' videos starting here", playlist_conference_path(slug: @event.slug)
      - if @conference.audio_recordings?
        \/
        = link_to 'audio', audio_playlist_conference_path(slug: @event.slug), method: :get
      - if @event.metadata['related'].present?
        \/
        = link_to 'related events', playlist_related_path(slug: @event.slug)

    - elsif @event.relive_present?
      .player.video
        .kiosk
        = render partial: 'frontend/shared/player_relive', locals: video_player_ivars

    - elsif @event.recordings.audio.present?
      .player.audio
        = render partial: 'frontend/shared/player_audio', locals: video_player_ivars


    - else
      No content found (yet?).

    %ul.metadata
      %li
        %span.icon.icon-clock-o
        = duration_in_minutes(@event.duration)
      %li
        %span.icon.icon-calendar-o{title: display_release_date_title(@event)}
        = @event.display_date
      - if !@event.release_date.nil? && ! @event.released_on_event_day?
        %li
          %span.icon.icon-upload{title: 'release date'}
          = @event.release_date.to_date
      %li
        %span.icon.icon-eye
        = @event.view_count
      - if @event.link.present?
        %li
          %span.icon.icon-external-link
          %a{href: @event.link} Fahrplan
      - if @event.doi.present?
        %li
          %span.icon.icon-external-link
          %a{href: @event.doi_url}
            = truncate(@event.doi, length: 20, separator: ' ', omission: '…')

    - if @event.description.present?
      /%h3 About
      %p.description
        = simple_format @event.description

    %h3 Download
    .download
      = render partial: 'frontend/shared/download', locals: { conference: @conference, event: @event }

      - if !@event.recordings.video.present? && @event.relive_present?
        Downloads will appear here, once final recordings are released.



    - if @event.metadata['related'].present?
      %h3 Related
      = render partial: 'frontend/shared/related', locals: { events: Frontend::Event.find(@event.related_event_ids(10)) }

    /%h3 Embed/Share
    .share
      = render partial: 'frontend/shared/embedshare', locals: { event: @event }

    - if @event.tags.present?
      %h3 Tags
      .tags
        - @event.tags.each do |tag|
          - if tag =~ /^[0-9]+/
            != link_for_global(tag)
          - else
            != link_for(@conference, tag)